// ============================================================
// TECHNOFEST 2026 — CENTRALIZED CONFIGURATION
// Edit this file to update all site-wide settings
// ============================================================

const CONFIG = {
  // ── Registration ─────────────────────────────────────────
  GOOGLE_FORM_URL: "https://forms.gle/BSXYKUSRFYHpS4iA9",

  // ── Event Info ────────────────────────────────────────────
  EVENT_NAME: "Technofest 2026",
  EVENT_DATE: "2026-09-30T00:00:00",   // ISO 8601 — local time
  EVENT_DATE_DISPLAY: "30 September 2026",
  EVENT_TAGLINE: "Where Technology Meets Talent",
  EVENT_TYPE: "Technical + Non-Technical Fest",

  // ── College / Organizer ───────────────────────────────────
  COLLEGE_NAME: "Anand Institute of Higher Technology",
  COLLEGE_SHORT: "AIHT",
  COLLEGE_TAGLINE: "An Autonomous Institution",
  COLLEGE_AFFILIATION: "Approved by AICTE, New Delhi. Affiliated to Anna University, Chennai.",
  COLLEGE_ACCREDITATION: "ISO 9001:2008 Certified Institution & Accredited by NBA",
  COLLEGE_ADDRESS: "Kalasalingam Nagar, IT Corridor, Old Mahabalipuram Road (OMR), Kazhipattur, Chennai – 603103, Tamil Nadu",
  COLLEGE_WEBSITE: "https://www.aiht.ac.in",
  VENUE: "Anand Institute of Higher Technology, OMR, Kazhipattur, Chennai – 603103",
  TIMING: "TO BE ANNOUNCED",
  REGISTRATION_DEADLINE: "TO BE ANNOUNCED",
  REGISTRATION_FEE: "TO BE ANNOUNCED",

  // ── Social Media ──────────────────────────────────────────
  SOCIAL: {
    instagram: "",                              // Add AIHT Instagram handle when available
    linkedin: "",                               // Add AIHT LinkedIn URL when available
    facebook: "https://www.facebook.com/aihtofficial",
    whatsapp: "",
  },

  // ── Contact ───────────────────────────────────────────────
  CONTACT_EMAIL: "principal@aiht.ac.in",
  CONTACT_PHONE: "+91 044-27471330",
  ADMISSION_PHONE: "+91 8012136666",
};

// ============================================================
// EVENTS DATA
// Edit descriptions/rules/details here without touching HTML
// ============================================================

const TECHNICAL_EVENTS = [
  {
    id: "stack-and-level",
    name: "Stack and Level",
    icon: "📚",
    svgIcon: "layers",
    category: "Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "mr-mechanic",
    name: "Mr. Mechanic",
    icon: "🔧",
    svgIcon: "wrench",
    category: "Technical",
    description: "Showcase your mechanical aptitude and engineering instincts. Identify, disassemble, repair and reassemble mechanical systems.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "mind-marathon",
    name: "Mind Marathon",
    icon: "🧠",
    svgIcon: "brain",
    category: "Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "prompt-battle",
    name: "Prompt Battle",
    icon: "🤖",
    svgIcon: "terminal",
    category: "Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "digital-cyber-detective",
    name: "Digital Cyber Detective",
    icon: "🕵️",
    svgIcon: "search",
    category: "Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "lab-to-market",
    name: "Lab to Market Launch",
    icon: "🚀",
    svgIcon: "rocket",
    category: "Technical",
    description: "Transform a technical concept into a market-ready product pitch. From prototype to pitch deck — show the world your startup mindset.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "prompt-heist",
    name: "Prompt Heist",
    icon: "🔑",
    svgIcon: "key",
    category: "Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "ai-rescure-mission",
    name: "AI Rescure Mission",
    icon: "🛟",
    svgIcon: "lifebuoy",
    category: "Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "best-manager",
    name: "Best Manager",
    icon: "👑",
    svgIcon: "users",
    category: "Technical",
    description: "Put your management and leadership skills to the test. Handle real-world business scenarios, make decisions under pressure and lead your team.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "circuit-debugging",
    name: "Circuit Debugging",
    icon: "⚡",
    svgIcon: "circuit",
    category: "Technical",
    description: "Identify and fix faults in electronic circuits. Test your hardware knowledge and problem-solving speed under time pressure.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
];

const NON_TECHNICAL_EVENTS = [
  {
    id: "cryptic-clues",
    name: "Cryptic Clues",
    icon: "🔍",
    svgIcon: "search",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "mystery-unlock-series",
    name: "Mystery Unlock Series",
    icon: "🔓",
    svgIcon: "lock",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "balanced-figures",
    name: "Balanced Figures",
    icon: "⚖️",
    svgIcon: "scale",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "escapex",
    name: "Escapex",
    icon: "🚪",
    svgIcon: "door",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "neuro-fusion",
    name: "Neuro Fusion",
    icon: "🧠",
    svgIcon: "brain",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "chill-flix",
    name: "Chill Flix",
    icon: "🎬",
    svgIcon: "film",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "the-reckoning",
    name: "The Reckoning",
    icon: "🔥",
    svgIcon: "flame",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "hanging-challenge",
    name: "Hanging Challenge",
    icon: "🧗",
    svgIcon: "activity",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "box-cricket",
    name: "Box Cricket",
    icon: "🏏",
    svgIcon: "bat",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "gym-challenge",
    name: "Gym Challenge",
    icon: "🏋️",
    svgIcon: "dumbbell",
    category: "Non-Technical",
    description: "Prove your physical strength and fitness in a range of exciting gym-based challenges. Compete, push your limits and inspire.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "crack-the-code",
    name: "Crack the Code",
    icon: "🔐",
    svgIcon: "code",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "game-of-memes",
    name: "Game of Memes",
    icon: "😂",
    svgIcon: "laugh",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "memory-matrix",
    name: "Memory Matrix",
    icon: "🧩",
    svgIcon: "grid",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "canvas-clash",
    name: "Canvas Clash",
    icon: "🎨",
    svgIcon: "palette",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "cine-mania",
    name: "Cine Mania",
    icon: "📺",
    svgIcon: "tv",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "cricket-auction",
    name: "Cricket Auction",
    icon: "🔨",
    svgIcon: "gavel",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "connection",
    name: "Connection",
    icon: "🔗",
    svgIcon: "link",
    category: "Non-Technical",
    description: "A networking and relationship-building challenge that tests your social skills, creativity and ability to connect ideas and people.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "ad-zap",
    name: "Ad Zap",
    icon: "📣",
    svgIcon: "megaphone",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "biofest-arena",
    name: "Biofest Arena",
    icon: "🧬",
    svgIcon: "dna",
    category: "Non-Technical",
    description: "Details will be announced soon.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "open-mic",
    name: "Open Mic Night",
    icon: "🎤",
    svgIcon: "mic",
    category: "Non-Technical",
    description: "Take the stage and share your voice. Stand-up comedy, poetry, singing or spoken word — all are welcome at Open Mic Night.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
];

// Export for use across the app
if (typeof module !== "undefined") {
  module.exports = { CONFIG, TECHNICAL_EVENTS, NON_TECHNICAL_EVENTS };
}
