// ============================================================
// TECHNOFEST 2026 — CENTRALIZED CONFIGURATION
// Edit this file to update all site-wide settings
// ============================================================

const CONFIG = {
  // ── Registration ─────────────────────────────────────────
  GOOGLE_FORM_URL: "https://forms.gle/BSXYKUSRFYHpS4iA9",

  // ── Event Info ────────────────────────────────────────────
  EVENT_NAME: "Technofest 2026",
  EVENT_DATE: "2026-09-30T00:00:00",   // ISO 8601 — local time
  EVENT_DATE_DISPLAY: "30 September 2026",
  EVENT_TAGLINE: "Where Technology Meets Talent",
  EVENT_TYPE: "Technical + Non-Technical Fest",

  // ── College / Organizer ───────────────────────────────────
  COLLEGE_NAME: "Anand Institute of Higher Technology",
  COLLEGE_SHORT: "AIHT",
  COLLEGE_TAGLINE: "An Autonomous Institution",
  COLLEGE_AFFILIATION: "Approved by AICTE, New Delhi. Affiliated to Anna University, Chennai.",
  COLLEGE_ACCREDITATION: "ISO 9001:2008 Certified Institution & Accredited by NBA",
  COLLEGE_ADDRESS: "Kalasalingam Nagar, IT Corridor, Old Mahabalipuram Road (OMR), Kazhipattur, Chennai – 603103, Tamil Nadu",
  COLLEGE_WEBSITE: "https://www.aiht.ac.in",
  VENUE: "Anand Institute of Higher Technology, OMR, Kazhipattur, Chennai – 603103",
  TIMING: "TO BE ANNOUNCED",
  REGISTRATION_DEADLINE: "TO BE ANNOUNCED",
  REGISTRATION_FEE: "TO BE ANNOUNCED",

  // ── Social Media ──────────────────────────────────────────
  SOCIAL: {
    instagram: "",                              // Add AIHT Instagram handle when available
    linkedin: "",                               // Add AIHT LinkedIn URL when available
    facebook: "https://www.facebook.com/aihtofficial",
    whatsapp: "",
  },

  // ── Contact ───────────────────────────────────────────────
  CONTACT_EMAIL: "principal@aiht.ac.in",
  CONTACT_PHONE: "+91 044-27471330",
  ADMISSION_PHONE: "+91 8012136666",
};

// ============================================================
// EVENTS DATA
// Edit descriptions/rules/details here without touching HTML
// ============================================================

const TECHNICAL_EVENTS = [
  {
    id: "paper-presentation",
    name: "Paper Presentation",
    icon: "📄",
    svgIcon: "document",
    category: "Technical",
    description: "Present your research ideas and innovative concepts before an expert panel. Showcase your technical knowledge and communication skills.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "circuit-debugging",
    name: "Circuit Debugging",
    icon: "⚡",
    svgIcon: "circuit",
    category: "Technical",
    description: "Identify and fix faults in electronic circuits. Test your hardware knowledge and problem-solving speed under time pressure.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "crack-the-interview",
    name: "Crack the Interview",
    icon: "💼",
    svgIcon: "briefcase",
    category: "Technical",
    description: "Simulate a real-world technical interview environment. Demonstrate your aptitude, technical knowledge and communication skills.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "scavenger-hunt",
    name: "Scavenger Hunt",
    icon: "🗺️",
    svgIcon: "map",
    category: "Technical",
    description: "Follow clues, solve puzzles and race to find the final objective. A thrilling challenge that tests logic, teamwork and quick thinking.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "pictograph-probe",
    name: "Pictograph Probe",
    icon: "📊",
    svgIcon: "chart",
    category: "Technical",
    description: "Decode, interpret and analyse pictorial data representations. Challenge your data visualisation and analytical thinking skills.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "algo-arena",
    name: "Algo Arena",
    icon: "💻",
    svgIcon: "code",
    category: "Technical",
    description: "A competitive programming challenge where speed and algorithmic thinking decide the winner. Solve problems and climb the leaderboard.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "mr-mechanic",
    name: "Mr. Mechanic",
    icon: "🔧",
    svgIcon: "wrench",
    category: "Technical",
    description: "Showcase your mechanical aptitude and engineering instincts. Identify, disassemble, repair and reassemble mechanical systems.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "best-manager",
    name: "Best Manager",
    icon: "👑",
    svgIcon: "users",
    category: "Technical",
    description: "Put your management and leadership skills to the test. Handle real-world business scenarios, make decisions under pressure and lead your team.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "lab-to-market",
    name: "Lab to Market Launch",
    icon: "🚀",
    svgIcon: "rocket",
    category: "Technical",
    description: "Transform a technical concept into a market-ready product pitch. From prototype to pitch deck — show the world your startup mindset.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
];

const NON_TECHNICAL_EVENTS = [
  {
    id: "connection",
    name: "Connection",
    icon: "🔗",
    svgIcon: "link",
    category: "Non-Technical",
    description: "A networking and relationship-building challenge that tests your social skills, creativity and ability to connect ideas and people.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "squid-game",
    name: "Squid Game",
    icon: "🎮",
    svgIcon: "gamepad",
    category: "Non-Technical",
    description: "Inspired by the global phenomenon — a series of thrilling challenges that test your nerve, strategy and endurance.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "chill-with-cini",
    name: "Chill with Cini",
    icon: "🎬",
    svgIcon: "film",
    category: "Non-Technical",
    description: "A cinema-themed entertainment event. Movie trivia, fun activities and creative challenges for every film enthusiast.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "best-out-of-waste",
    name: "Best out of Waste",
    icon: "♻️",
    svgIcon: "recycle",
    category: "Non-Technical",
    description: "Create something remarkable from discarded materials. Unleash your creativity and commitment to sustainability.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "gym-challenge",
    name: "Gym Challenge",
    icon: "🏋️",
    svgIcon: "dumbbell",
    category: "Non-Technical",
    description: "Prove your physical strength and fitness in a range of exciting gym-based challenges. Compete, push your limits and inspire.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "open-mic",
    name: "Open Mic Night",
    icon: "🎤",
    svgIcon: "mic",
    category: "Non-Technical",
    description: "Take the stage and share your voice. Stand-up comedy, poetry, singing or spoken word — all are welcome at Open Mic Night.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "eight-leg-pentathlon",
    name: "Eight Leg Pentathlon",
    icon: "🏃",
    svgIcon: "activity",
    category: "Non-Technical",
    description: "A five-discipline team event requiring coordination, agility and collective effort. A true test of teamwork and athletic spirit.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "high-head-pyramid",
    name: "High Head Pyramid",
    icon: "🏛️",
    svgIcon: "pyramid",
    category: "Non-Technical",
    description: "Build the tallest, most stable human or physical pyramid. A challenge of balance, trust and structural creativity.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "test-your-luck",
    name: "Test your Luck",
    icon: "🎲",
    svgIcon: "dice",
    category: "Non-Technical",
    description: "Feeling lucky? A fun, chance-based event with exciting twists. Sometimes fortune favours the bold!",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "alpha-decode",
    name: "Alpha Decode",
    icon: "🔐",
    svgIcon: "lock",
    category: "Non-Technical",
    description: "Crack codes, decipher patterns and solve puzzles in this brain-bending decoding challenge. Sharp minds will prevail.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
  {
    id: "retro-rewind",
    name: "Retro Rewind",
    icon: "📺",
    svgIcon: "tv",
    category: "Non-Technical",
    description: "A nostalgic trip through pop culture, retro games and classic entertainment. Relive the past in this fun cultural quiz and activity event.",
    rules: [],
    eligibility: "Details will be announced soon.",
    teamSize: "Details will be announced soon.",
    duration: "Details will be announced soon.",
    venue: "Details will be announced soon.",
    coordinators: [],
    additionalInfo: "",
  },
];

// Export for use across the app
if (typeof module !== "undefined") {
  module.exports = { CONFIG, TECHNICAL_EVENTS, NON_TECHNICAL_EVENTS };
}
